Repository Algo-morgo/algorithm-study, pull requests merged in 2024-08, with the labels that each got.

#47 [정필모] 20240730 풀이 제출
  week9/leetcode/1653-minimum-deletions-to-make-string-balanced/itsmo1031.java
  week9/programmers/118669-등산코스-정하기/itsmo1031.java
Labels: 🤔 Needs Improvement

#51 [이경배] 240731 풀이 제출
  week9/leetcode/1105-filling-bookcase-shelves/rglley.java
  week9/programmers/68645-삼각-달팽이/rglley.java
Labels: ✅ Solved

#50 [정필모] 240731 풀이 제출
  week9/leetcode/1105-filling-bookcase-shelves/itsmo1031.java
  week9/programmers/68645-삼각-달팽이/itsmo1031.java
Labels: 🔥 Challenging, 🤔 Needs Improvement

#52 [김세민] 240801 풀이 제출
  week9/leetcode/2678-number-of-senior-citizens/kimgiraffe.java
  week9/programmers/12920-선입-선출-스케줄링/kimgiraffe.java
Labels: 🤔 Needs Improvement

#54 [이경배] 240801 풀이 제출
  week9/leetcode/2678-number-of-senior-citizens/rglley.java
  week9/programmers/12920-선입-선출-스케줄링/rglley.java
Labels: 🔥 Challenging

#53 [정필모] 240801 풀이 제출
  week9/leetcode/2678-number-of-senior-citizens/itsmo1031.java
  week9/programmers/12920-선입-선출-스케줄링/itsmo1031.java
Labels: 🔥 Challenging

#55 [김세민] 240802 풀이 제출
  week9/leetcode/2134-minimum-swaps-to-group-all-1s-together-ii/kimgiraffe.java
  week9/programmers/118667-두-큐-합-같게-만들기/kimgiraffe.java
Labels: 🔥 Challenging

#56 [이경배] 240802 풀이 제출
  week9/leetcode/2134-minimum-swaps-to-group-all-1s-together-ii/rglley.java
  week9/programmers/118667-두-큐-합-같게-만들기/rglley.java
Labels: 🔥 Challenging

#60 [정필모] 240805 풀이 제출
  week10/leetcode/2053-kth-distinct-string-in-an-array/itsmo1031.java
  week10/programmers/148653-마법의-엘리베이터/itsmo1031.java
Labels: 🤔 Needs Improvement

#61 [김세민] 240805 풀이 제출
  week10/leetcode/2053-kth-distinct-string-in-an-array/kimgiraffe.java
  week10/programmers/148653-마법의-엘리베이터/kimgiraffe.java
Labels: ✅ Solved

#59 [이경배] 240805 풀이 제출
  week10/leetcode/2053-kth-distinct-string-in-an-array/rglley.java
  week10/programmers/148653-마법의-엘리베이터/rglley.java
Labels: ✅ Solved

#63 [이경배] 240806 풀이 제출
  week10/leetcode/3016-minimum-number-of-pushes-to-type-word-ii/rglley.java
  week10/programmers/60063-블록-이동하기/rglley.java
Labels: 🔥 Challenging

#57 [정필모] 20240802 풀이 제출
  week9/leetcode/2134-minimum-swaps-to-group-all-1s-together-ii/itsmo1031.java
  week9/programmers/118667-두-큐-합-같게-만들기/itsmo1031.java
Labels: ✅ Solved

#62 [정필모] 240806 풀이 제출
  week10/leetcode/3016-minimum-number-of-pushes-to-type-word-ii/itsmo1031.java
  week10/programmers/60063-블록-이동하기/itsmo1031.java
Labels: 🤔 Needs Improvement

#64 [정필모] 240807 풀이 제출
  week10/leetcode/273-integer-to-english-words/itsmo1031.java
  week10/programmers/72411-메뉴-리뉴얼/itsmo1031.java
Labels: ✅ Solved

#65 [이경배] 240807 풀이 제출
  week10/leetcode/273-integer-to-english-words/rglley.java
  week10/programmers/72411-메뉴-리뉴얼/rglley.java
Labels: ✅ Solved
