Repository Algo-morgo/algorithm-study, pull requests merged in 2024-07, with the labels that each got.

#1 [정필모] 2024-07-08 풀이 제출
  week6/leetcode/1823-find-the-winner-of-the-circular-game/itsmo1031.java
  week6/programmers/72414-광고-삽입/itsmo1031.java
Labels: 🔥 Challenging, 🤔 Needs Improvement

#2 [정필모] 2024-07-09 풀이 제출
  week6/leetcode/1701-average-waiting-time/itsmo1031.java
  week6/programmers/76502-괄호-회전하기/itsmo1031.java
Labels: ✅ Solved

#3 [정필모] 2024-07-10 풀이 제출
  week6/leetcode/1598-crawler-log-folder/itsmo1031.java
  week6/programmers/150365-미로-탈출-명령어/itsmo1031.java
Labels: ✅ Solved

#5 [정필모] 2024-07-11 풀이 제출
  week6/leetcode/1190-reverse-substrings-between-each-pair-of-parentheses/itsmo1031.java
  week6/programmers/64065-튜플/itsmo1031.java
Labels: 🤔 Needs Improvement

#6 [정필모] 2024-07-12 풀이 제출
  week6/leetcode/1717-maximum-score-from-removing-substrings/itsmo1031.java
  week6/programmers/17677-뉴스-클러스터링/itsmo1031.java
Labels: 🤔 Needs Improvement

#4 [김세민] 2024-07-08 풀이 제출
  week6/leetcode/1190-reverse-substrings-between-each-pair-of-parentheses/kimgiraffe.java
  week6/leetcode/1598-crawler-log-folder/kimgiraffe.java
  week6/leetcode/1701-average-waiting-time/kimgiraffe.java
  week6/leetcode/1717-maximum-score-from-removing-substrings/kimgiraffe.java
  week6/leetcode/1823-find-the-winner-of-the-circular-game/kimgiraffe.java
  week6/programmers/150365-미로-탈출-명령어/kimgiraffe.java
  week6/programmers/17677-뉴스-클러스터링/kimgiraffe.java
  week6/programmers/64065-튜플/kimgiraffe.java
  week6/programmers/72414-광고-삽입/kimgiraffe.java
  week6/programmers/76502-괄호-회전하기/kimgiraffe.java
Labels: 🔥 Challenging, 🤔 Needs Improvement

#10 [김세민] 240715
  week7/leetcode/2196-create-binary-tree-from-descriptions/kimgiraffe.java
  week7/programmers/17687-N진수-게임/kimgiraffe.java
Labels: ✅ Solved

#11 [정필모] 240715 풀이 제출
  week7/leetcode/2196-create-binary-tree-from-descriptions/itsmo1031.java
  week7/programmers/17687-N진수-게임/itsmo1031.java
Labels: 🤔 Needs Improvement

#12 [이경배] 2024. 07. 15. 풀이 제출
  week7/leetcode/2196-create-binary-tree-from-descriptions/rglley.java
  week7/programmers/17687-N진수-게임/rglley.java
Labels: 🤔 Needs Improvement

#14 [김세민] 240716 풀이 제출
  week7/leetcode/2096-step-by-step-directions-from-a-binary-tree-node-to-another/kimgiraffe.java
  week7/programmers/60062-외벽-점검/kimgiraffe.java
Labels: 🔥 Challenging

#13 [정필모] 240716 풀이 제출
  week7/leetcode/2096-step-by-step-directions-from-a-binary-tree-node-to-another/itsmo1031.java
  week7/programmers/60062-외벽-점검/itsmo1031.java
Labels: 🙋‍♂️ Help

#16 [김세민] 240717 풀이 제출
  week7/leetcode/1110-delete-nodes-and-return-forest/kimgiraffe.java
  week7/programmers/92335-k진수에서-소수-개수-구하기/kimgiraffe.java
Labels: ✅ Solved

#15 [이경배] 240716 풀이 제출
  week7/leetcode/2096-step-by-step-directions-from-a-binary-tree-node-to-another/rglley.java
  week7/programmers/60062-외벽-점검/rglley.java
Labels: 🙋‍♂️ Help

#17 [정필모] 240717 문제 풀이 제출
  week7/leetcode/1110-delete-nodes-and-return-forest/itsmo1031.java
  week7/programmers/92335-k진수에서-소수-개수-구하기/itsmo1031.java
Labels: ✅ Solved

#19 [김세민] 240718 문제 풀이 제출
  week7/leetcode/1530-number-of-good-leaf-nodes-pairs/kimgiraffe.java
  week7/programmers/77886-110-옮기기/kimgiraffe.java
Labels: 🔥 Challenging, 🤔 Needs Improvement

#20 [정필모] 240718 풀이 제출
  week7/leetcode/1530-number-of-good-leaf-nodes-pairs/itsmo1031.java
  week7/programmers/77886-110-옮기기/itsmo1031.java
Labels: 🔥 Challenging

#23 [김세민] 240719 풀이 제출
  week7/leetcode/1380-lucky-numbers-in-a-matrix/kimgiraffe.java
  week7/programmers/17684-압축/kimgiraffe.java
Labels: ✅ Solved

#21 [이경배] 240718 풀이 제출
  week7/leetcode/1530-number-of-good-leaf-nodes-pairs/rglley.java
  week7/programmers/77886-110-옮기기/rglley.java
Labels: 🔥 Challenging, 🙋‍♂️ Help

#26 [김세민] 240722 풀이 제출
  week8/leetcode/2418-sort-the-people/kimgiraffe.java
  week8/programmers/17686-파일명-정렬/kimgiraffe.java
Labels: ✅ Solved

#24 [이경배] 240719 풀이 제출
  week7/leetcode/1380-lucky-numbers-in-a-matrix/rglley.java
  week7/programmers/17684-압축/rglley.java
Labels: ✅ Solved

#27 [정필모] 240722 풀이 제출
  week8/leetcode/2418-sort-the-people/itsmo1031.java
  week8/programmers/17686-파일명-정렬/itsmo1031.java
Labels: ✅ Solved

#29 [정필모] 20240723 풀이 제출
  week8/leetcode/1636-sort-array-by-increasing-frequency/itsmo1031.java
  week8/programmers/150367-표현-가능한-이진트리/itsmo1031.java
Labels: 🤔 Needs Improvement

#30 [김세민] 240723 풀이 제출
  week8/leetcode/1636-sort-array-by-increasing-frequency/kimgiraffe.java
  week8/programmers/150367-표현-가능한-이진트리/kimgiraffe.java
Labels: 🔥 Challenging

#28 [이경배] 240722 풀이 제출
  week8/leetcode/2418-sort-the-people/rglley.java
  week8/programmers/17686-파일명-정렬/rglley.java
Labels: ✅ Solved

#31 [정필모] 20240724 풀이 제출
  week8/leetcode/2191-sort-the-jumbled-numbers/itsmo1031.java
  week8/programmers/17679-프렌즈4블록/itsmo1031.java
Labels: 🤔 Needs Improvement

#32 [김세민] 240724 풀이 제출
  week8/leetcode/2191-sort-the-jumbled-numbers/kimgiraffe.java
  week8/programmers/17679-프렌즈4블록/kimgiraffe.java
Labels: 🤔 Needs Improvement

#38 [이경배] 240725 풀이 제출
  week8/leetcode/912-sort-an-array/rglley.java
  week8/programmers/70130-스타-수열/rglley.java
Labels: 🔥 Challenging

#39 [김세민] 240725 풀이 제출
  week8/leetcode/912-sort-an-array/kimgiraffe.java
  week8/programmers/70130-스타-수열/kimgiraffe.java
Labels: ✅ Solved

#40 [김세민] 240726 풀이 제출
  week8/leetcode/1334-find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/kimgiraffe.java
  week8/programmers/77885-2개-이하로-다른-비트/kimgiraffe.java
Labels: 🤔 Needs Improvement

#34 [정필모] 240725 풀이 제출
  week8/leetcode/912-sort-an-array/itsmo1031.java
  week8/programmers/70130-스타-수열/itsmo1031.java
Labels: 🔥 Challenging, 🤔 Needs Improvement

#43 [김세민] 240729 풀이 제출
  week9/leetcode/1395-count-number-of-teams/kimgiraffe.java
  week9/programmers/68936-쿼드압축-후-개수-세기/kimgiraffe.java
Labels: 🤔 Needs Improvement, ✅ Solved

#41 [이경배] 240726 풀이 제출
  week8/leetcode/1334-find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/rglley.java
  week8/programmers/77885-2개-이하로-다른-비트/rglley.java
Labels: 🤔 Needs Improvement

#35 [이경배] 240724 풀이 제출
  week8/leetcode/2191-sort-the-jumbled-numbers/rglley.java
  week8/programmers/17679-프렌즈4블록/rglley.java
Labels: 🤔 Needs Improvement

#45 [이경배] 240729 풀이 제출
  week9/leetcode/1395-count-number-of-teams/rglley.java
  week9/programmers/68936-쿼드압축-후-개수-세기/rglley.java
Labels: ✅ Solved

#44 [정필모] 20240729 풀이 제출
  week9/leetcode/1395-count-number-of-teams/itsmo1031.java
  week9/programmers/68936-쿼드압축-후-개수-세기/itsmo1031.java
Labels: 🤔 Needs Improvement

#46 [김세민] 240730 풀이 제출
  week9/leetcode/1653-minimum-deletions-to-make-string-balanced/kimgiraffe.java
  week9/programmers/118669-등산코스-정하기/kimgiraffe.java
Labels: 🤔 Needs Improvement, ✅ Solved

#49 [김세민] 240731 풀이 제출
  week9/leetcode/1105-filling-bookcase-shelves/kimgiraffe.java
  week9/programmers/68645-삼각-달팽이/kimgiraffe.java
Labels: ✅ Solved

#48 [이경배] 240730 풀이 제출
  week9/leetcode/1653-minimum-deletions-to-make-string-balanced/rglley.java
  week9/programmers/118669-등산코스-정하기/rglley.java
Labels: 🔥 Challenging
